[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rmtree"
version = "0.2.0a"
requires-python = ">=3.10"
readme = "README.md"
license = { file = "LICENSE" }

description = "Convert the file tree from the reMarkable tablet to PDFs"
authors = ["Seb-sti1"]
license = "MIT"
dependencies = [
    "fpdf2",
    "pypdf",
    "cairosvg",
    "rmc@git+https://github.com/Seb-sti1/rmc.git@bdb353feff968c9061fd4232699e58e95d4429db",
    "rmscene",
    "tqdm",
]


[project.scripts]
projecthub = "rmtree.main:main"
